# -*- Mode: Python; tab-width: 2; indent-tabs-mode:nil; -*-
# vim: set ts=2 et sw=2 tw=80:
# ***** BEGIN LICENSE BLOCK *****
# Version: Apache License 2.0
#
# Copyright (c) 2011 Design Science, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Contributor(s):
#   Frederic Wang <fred.wang@free.fr> (original author)
#
# ***** END LICENSE BLOCK *****

from config import *
import string
import subprocess

def declarePythonString(aStream, aName, aValue):
    print >>aStream, aName + " = '" + aValue + "'"

def declarePythonInteger(aStream, aName, aValue):
    print >>aStream, aName + " = " + str(aValue)

def declarePythonStringArray(aStream, aName, aValue):
    aStream.write(aName + " = [")
    if (len(aValue) > 0):
        aStream.write("'" + aValue[0] + "'")
        for i in range(1, len(aValue)):
            aStream.write(",'" + aValue[i] + "'")
    aStream.write("]\n")

def declarePhpString(aStream, aName, aValue):
    print >>aStream, "$" + aName + " = '" + aValue + "';"

def declarePhpInteger(aStream, aName, aValue):
    print >>aStream, "$" + aName + " = " + str(aValue) + ";"

def declarePhpStringArray(aStream, aName, aValue):
    aStream.write("$" + aName + " = array(")
    if (len(aValue) > 0):
        aStream.write("'" + aValue[0] + "'")
        for i in range(1, len(aValue)):
            aStream.write(",'" + aValue[i] + "'")
    aStream.write(");\n")
    
# Generate web/.htaccess
f_in = file("web/htaccess-template", "r")
content = string.replace(f_in.read(), "QA_PASSWORD_FILE", QA_PASSWORD_FILE)
f_in.close()
f_out = file("web/.htaccess", "w")
print >>f_out, "# This file is automatically generated from htaccess-template."
f_out.write(content)
f_out.close()

# Create web/config.py
f_out = open("testRunner/config.py", "w")
print >>f_out, "# This file is automatically generated. Do not edit."

declarePythonString(f_out, "TASK_HANDLER_HOST", TASK_HANDLER_HOST)
declarePythonInteger(f_out, "TASK_HANDLER_PORT", TASK_HANDLER_PORT)

declarePythonStringArray(f_out, "KNOWN_HOSTS", KNOWN_HOSTS)
declarePythonInteger(f_out, "DEFAULT_SELENIUM_PORT", DEFAULT_SELENIUM_PORT)
declarePythonString(f_out, "DEFAULT_MATHJAX_PATH", DEFAULT_MATHJAX_PATH)
declarePythonString(f_out, "DEFAULT_MATHJAX_TEST_PATH",
                    DEFAULT_MATHJAX_TEST_PATH)
declarePythonInteger(f_out, "DEFAULT_TIMEOUT", DEFAULT_TIMEOUT)

declarePythonString(f_out, "MATHJAX_WEB_URI", MATHJAX_WEB_URI)

declarePythonString(f_out, "MATHJAX_WEB_PATH", MATHJAX_WEB_PATH)
declarePythonString(f_out, "MATHJAX_TESTSUITE_PATH", MATHJAX_TESTSUITE_PATH)

f_out.close()

# Create web/config.php
f_out = open("web/config.php", "w")
print >>f_out, "<?php"
print >>f_out, "/* This file is automatically generated. Do not edit. */"

declarePhpString(f_out, "TASK_HANDLER_HOST", TASK_HANDLER_HOST)
declarePhpInteger(f_out, "TASK_HANDLER_PORT", TASK_HANDLER_PORT)

declarePhpString(f_out, "DEFAULT_TASK_NAME", DEFAULT_TASK_NAME)
declarePhpStringArray(f_out, "KNOWN_HOSTS", KNOWN_HOSTS)
declarePhpInteger(f_out, "DEFAULT_SELENIUM_PORT", DEFAULT_SELENIUM_PORT)
declarePhpString(f_out, "DEFAULT_MATHJAX_PATH", DEFAULT_MATHJAX_PATH)
declarePhpString(f_out, "DEFAULT_MATHJAX_TEST_PATH",
                 DEFAULT_MATHJAX_TEST_PATH)
declarePhpInteger(f_out, "DEFAULT_TIMEOUT", DEFAULT_TIMEOUT)

declarePhpStringArray(f_out, "BROWSER_LIST", BROWSER_LIST)
declarePhpStringArray(f_out, "OS_LIST", OS_LIST)
declarePhpStringArray(f_out, "BROWSER_MODE_LIST", BROWSER_MODE_LIST)
declarePhpStringArray(f_out, "FONT_LIST", FONT_LIST)

print >>f_out, "?>"
f_out.close()
