<!--
    Copyright 2012-2015 MathJax Consortium, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  
  <xsl:strip-space elements="*"/>

  <xsl:template match="*">
    <xsl:apply-templates select="*"/>
  </xsl:template>

  <xsl:template match="body">
    <xsl:comment>This file is automatically generated. Do not edit</xsl:comment>
    <root><xsl:apply-templates select="*"/></root>
  </xsl:template>

  <xsl:template match="table">
    <issueList><xsl:apply-templates select="*"/></issueList>
  </xsl:template>

  <xsl:template match="tr[@class]">
    <xsl:if test="@class">
      <issue>
        <xsl:attribute name="id">
          <xsl:value-of select="normalize-space(./td[@class='number'])"/>
        </xsl:attribute>

        <xsl:for-each select="td[@class='info']/div/h3/span[@data-name]">
          <label><xsl:value-of select="."/></label>
        </xsl:for-each>
      </issue>
    </xsl:if>
  </xsl:template>

  <xsl:template match="div">
    <xsl:choose>
      <xsl:when test="@class = 'pagination'">  
        <pagination>
          <xsl:attribute name="numberOfPages">
            <xsl:value-of select="count(*) - 2"/>
          </xsl:attribute>
        </pagination>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="*"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

</xsl:stylesheet>
